		</div><!-- closes main -->
	</div><!-- closes content wrap -->	
	<div id="footer">
		<p> &copy; 2012 <strong>Drew Kitch</strong> | Design by: <a href="http://www.styleshout.com/">styleshout</a> | Valid <a href="http://validator.w3.org/check?uri=referer">XHTML</a> | <a href="http://jigsaw.w3.org/css-validator/check/referer">CSS</a> &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; <a href="http://www.free-css.com/">Home</a>&nbsp;|&nbsp; <a href="http://www.free-css.com/">Sitemap</a>&nbsp;|&nbsp; <a href="http://www.free-css.com/">RSS Feed</a> </p>
	</div><!-- closes footer -->
</div><!-- closes-wrap -->
</body>
</html>