<?php
echo "<?xml version='1.0' encoding='UTF-8'?>";
?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN"
"http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
<head>
<title>BatteryQR - Track and Eliminate bad batteries with QR codes</title>
<meta name="description" content="Track your two-way radio batteries with QR codes on BatteryQR and eliminate bad batteries once and for all." />
<meta name="keywords" content="battery,qr" />
<link rel="icon" type="image/x-icon" href="favicon.ico" />
<link rel="stylesheet" type="text/css" rev="stylesheet" href="css/styles.css" media="screen" />
<link rel="stylesheet" href="css/mobile.css" type="text/css" media="handheld" />
<link rel="stylesheet" media="screen and (max-device-width: 480px)" href="css/mobile.css" />

<meta name="viewport" content="initial-scale=1, maximum-scale=1">
<meta http-equiv="Content-Style-Type" content="text/css" />

</head>
<body>
<div id="wrap">
	<div id="header">
		<h1 id="logo-text">Battery QR</h1>
		<img id="logo-img" src="images/battery.png" alt="battery_2.png" />
		<h2 id="slogan">eliminate "bad batteries" once and for all</h2>
		<div id="header-links">
			<p></p>
		</div>
	</div>
	<div id="menu">
		<ul><li></li></ul>
	</div>
	<div id="content-wrap">
		<div id="sidebar">
			<div class="left-box">

      			</div>
      			<br />
      			<div class="left-box">

      			</div>
      			<br />
      			<div class="left-box">
        			<blockquote>

      			</div>    			
		</div>	
		<div id="main">